version: '3'
services:


  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - global-network

  postgres_admin:
    image: dpage/pgadmin4
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '15432:80'
    networks:
      - global-network

  backend:
    build:
      context: .
      dockerfile: ./apps/microservice-books-club/dockerfile.dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
      - auth
      - books
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev microservice-books-club # overrides CMD from dockerfile
    networks:
      - global-network

networks:
  global-network:
    driver: bridge
