global:
  scrape_interval:     15s
  evaluation_interval: 120s
  external_labels:
      monitor: 'my-project'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
         - targets: ['localhost:9090','cadvisor:8080','node-exporter:9100']

  - job_name: 'nestjs-app'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /api/v1/metrics
    static_configs:
     - targets: ['api:3000']

